const db = require("../config/db");
const { types, typeEffectivness, moves, pokemons, pokemonsTypes } = require("./schema");
const { parseIntegerStrict } = require('../utils/parsesForPrimitives');

const typesNames = {
    1: "normal",
    2: "fighting",
    3: "flying",
    4: "poison",
    5: "ground",
    6: "rock",
    7: "bug",
    8: "ghost",
    9: "steel",
    10: "fire",
    11: "water",
    12: "grass",
    13: "electric",
    14: "psychic",
    15: "ice",
    16: "dragon",
    17: "dark",
    18: "fairy",
}

const getTypeName = (q) => typesNames[q];
const getId = (q) => parseIntegerStrict(Object.keys(typesNames).find(val => typesNames[val] == q));

await db.insert(types).values([
    { id: 1, name: "normal" },
    { id: 2, name: "fighting" },
    { id: 3, name: "flying" },
    { id: 4, name: "poison" },
    { id: 5, name: "ground" },
    { id: 6, name: "rock" },
    { id: 7, name: "bug" },
    { id: 8, name: "ghost" },
    { id: 9, name: "steel" },
    { id: 10, name: "fire" },
    { id: 11, name: "water" },
    { id: 12, name: "grass" },
    { id: 13, name: "electric" },
    { id: 14, name: "psychic" },
    { id: 15, name: "ice" },
    { id: 16, name: "dragon" },
    { id: 17, name: "dark" },
    { id: 18, name: "fairy" },
]);

await db.insert(typeEffectivness).values([
    { attackerTypeId: getId('normal'), defenderTypeId: getId('rock'), effectivness: 0.5 },
    { attackerTypeId: getId('normal'), defenderTypeId: getId('ghost'), effectivness: 0 },
    { attackerTypeId: getId('normal'), defenderTypeId: getId('steel'), effectivness: 0.5 },
    { attackerTypeId: getId('fire'), defenderTypeId: getId('fire'), effectivness: 0.5 },
    { attackerTypeId: getId('fire'), defenderTypeId: getId('water'), effectivness: 0.5 },
    { attackerTypeId: getId('fire'), defenderTypeId: getId('grass'), effectivness: 2 },
    { attackerTypeId: getId('fire'), defenderTypeId: getId('bug'), effectivness: 2 },
    { attackerTypeId: getId('fire'), defenderTypeId: getId('rock'), effectivness: 0.5 },
    { attackerTypeId: getId('fire'), defenderTypeId: getId('dragon'), effectivness: 0.5 },
    { attackerTypeId: getId('fire'), defenderTypeId: getId('steel'), effectivness: 2 },
    { attackerTypeId: getId('water'), defenderTypeId: getId('fire'), effectivness: 2 },
    { attackerTypeId: getId('water'), defenderTypeId: getId('water'), effectivness: 0.5 },
    { attackerTypeId: getId('water'), defenderTypeId: getId('grass'), effectivness: 0.5 },
    { attackerTypeId: getId('water'), defenderTypeId: getId('ground'), effectivness: 2 },
    { attackerTypeId: getId('water'), defenderTypeId: getId('rock'), effectivness: 2 },
    { attackerTypeId: getId('water'), defenderTypeId: getId('dragon'), effectivness: 0.5 },
    { attackerTypeId: getId('electric'), defenderTypeId: getId('water'), effectivness: 2 },
    { attackerTypeId: getId('electric'), defenderTypeId: getId('electric'), effectivness: 0.5 },
    { attackerTypeId: getId('electric'), defenderTypeId: getId('grass'), effectivness: 0.5 },
    { attackerTypeId: getId('electric'), defenderTypeId: getId('ground'), effectivness: 0 },
    { attackerTypeId: getId('electric'), defenderTypeId: getId('flying'), effectivness: 2 },
    { attackerTypeId: getId('electric'), defenderTypeId: getId('dragon'), effectivness: 0.5 },
    { attackerTypeId: getId('grass'), defenderTypeId: getId('fire'), effectivness: 0.5 },
    { attackerTypeId: getId('grass'), defenderTypeId: getId('water'), effectivness: 2 },
    { attackerTypeId: getId('grass'), defenderTypeId: getId('grass'), effectivness: 0.5 },
    { attackerTypeId: getId('grass'), defenderTypeId: getId('posion'), effectivness: 0.5 },
    { attackerTypeId: getId('grass'), defenderTypeId: getId('ground'), effectivness: 2 },
    { attackerTypeId: getId('grass'), defenderTypeId: getId('rock'), effectivness: 2 },
    { attackerTypeId: getId('grass'), defenderTypeId: getId('bug'), effectivness: 0.5 },
    { attackerTypeId: getId('grass'), defenderTypeId: getId('dragon'), effectivness: 0.5 },
    { attackerTypeId: getId('grass'), defenderTypeId: getId('steel'), effectivness: 0.5 },
    { attackerTypeId: getId('ice'), defenderTypeId: getId('fire'), effectivness: 0.5 },
    { attackerTypeId: getId('ice'), defenderTypeId: getId('water'), effectivness: 0.5 },
    { attackerTypeId: getId('ice'), defenderTypeId: getId('ice'), effectivness: 0.5 },
    { attackerTypeId: getId('ice'), defenderTypeId: getId('steel'), effectivness: 0.5 },
    { attackerTypeId: getId('ice'), defenderTypeId: getId('grass'), effectivness: 2 },
    { attackerTypeId: getId('ice'), defenderTypeId: getId('ground'), effectivness: 2 },
    { attackerTypeId: getId('ice'), defenderTypeId: getId('flying'), effectivness: 2 },
    { attackerTypeId: getId('ice'), defenderTypeId: getId('dragon'), effectivness: 2 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('normal'), effectivness: 2 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('ice'), effectivness: 2 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('rock'), effectivness: 2 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('dark'), effectivness: 2 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('steel'), effectivness: 2 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('fairy'), effectivness: 0.5 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('posion'), effectivness: 0.5 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('flying'), effectivness: 0.5 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('psychic'), effectivness: 0.5 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('bug'), effectivness: 0.5 },
    { attackerTypeId: getId('fighting'), defenderTypeId: getId('ghost'), effectivness: 0 },
    { attackerTypeId: getId('posion'), defenderTypeId: getId('grass'), effectivness: 2 },
    { attackerTypeId: getId('posion'), defenderTypeId: getId('posion'), effectivness: 0.5 },
    { attackerTypeId: getId('posion'), defenderTypeId: getId('ground'), effectivness: 0.5 },
    { attackerTypeId: getId('posion'), defenderTypeId: getId('rock'), effectivness: 0.5 },
    { attackerTypeId: getId('posion'), defenderTypeId: getId('ghost'), effectivness: 0.5 },
    { attackerTypeId: getId('posion'), defenderTypeId: getId('steel'), effectivness: 0 },
    { attackerTypeId: getId('posion'), defenderTypeId: getId('fairy'), effectivness: 2 },
    { attackerTypeId: getId('ground'), defenderTypeId: getId('fire'), effectivness: 2 },
    { attackerTypeId: getId('ground'), defenderTypeId: getId('electric'), effectivness: 2 },
    { attackerTypeId: getId('ground'), defenderTypeId: getId('grass'), effectivness: 0.5 },
    { attackerTypeId: getId('ground'), defenderTypeId: getId('posion'), effectivness: 2 },
    { attackerTypeId: getId('ground'), defenderTypeId: getId('flying'), effectivness: 0 },
    { attackerTypeId: getId('ground'), defenderTypeId: getId('bug'), effectivness: 0.5 },
    { attackerTypeId: getId('ground'), defenderTypeId: getId('rock'), effectivness: 2 },
    { attackerTypeId: getId('ground'), defenderTypeId: getId('steel'), effectivness: 2 },
    { attackerTypeId: getId('flying'), defenderTypeId: getId('electric'), effectivness: 0.5 },
    { attackerTypeId: getId('flying'), defenderTypeId: getId('grass'), effectivness: 2 },
    { attackerTypeId: getId('flying'), defenderTypeId: getId('fighting'), effectivness: 2 },
    { attackerTypeId: getId('flying'), defenderTypeId: getId('bug'), effectivness: 2 },
    { attackerTypeId: getId('flying'), defenderTypeId: getId('rock'), effectivness: 0.5 },
    { attackerTypeId: getId('flying'), defenderTypeId: getId('steel'), effectivness: 0.5 },
    { attackerTypeId: getId('psychic'), defenderTypeId: getId('fighting'), effectivness: 2 },
    { attackerTypeId: getId('psychic'), defenderTypeId: getId('posion'), effectivness: 2 },
    { attackerTypeId: getId('psychic'), defenderTypeId: getId('psychic'), effectivness: 0.5 },
    { attackerTypeId: getId('psychic'), defenderTypeId: getId('dark'), effectivness: 0 },
    { attackerTypeId: getId('psychic'), defenderTypeId: getId('steel'), effectivness: 0.5 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('fire'), effectivness: 0.5 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('grass'), effectivness: 2 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('fighting'), effectivness: 0.5 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('posion'), effectivness: 0.5 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('flying'), effectivness: 0.5 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('psychic'), effectivness: 2 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('ghost'), effectivness: 0.5 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('dark'), effectivness: 2 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('steel'), effectivness: 0.5 },
    { attackerTypeId: getId('bug'), defenderTypeId: getId('fairy'), effectivness: 0.5 },
    { attackerTypeId: getId('rock'), defenderTypeId: getId('fire'), effectivness: 2 },
    { attackerTypeId: getId('rock'), defenderTypeId: getId('ice'), effectivness: 2 },
    { attackerTypeId: getId('rock'), defenderTypeId: getId('fighting'), effectivness: 0.5 },
    { attackerTypeId: getId('rock'), defenderTypeId: getId('ground'), effectivness: 0.5 },
    { attackerTypeId: getId('rock'), defenderTypeId: getId('flying'), effectivness: 2 },
    { attackerTypeId: getId('rock'), defenderTypeId: getId('bug'), effectivness: 2 },
    { attackerTypeId: getId('rock'), defenderTypeId: getId('steel'), effectivness: 0.5 },
    { attackerTypeId: getId('ghost'), defenderTypeId: getId('normal'), effectivness: 0 },
    { attackerTypeId: getId('ghost'), defenderTypeId: getId('psychic'), effectivness: 2 },
    { attackerTypeId: getId('ghost'), defenderTypeId: getId('ghost'), effectivness: 2 },
    { attackerTypeId: getId('ghost'), defenderTypeId: getId('dark'), effectivness: 0.5 },
    { attackerTypeId: getId('dragon'), defenderTypeId: getId('dragon'), effectivness: 2 },
    { attackerTypeId: getId('dragon'), defenderTypeId: getId('steel'), effectivness: 0.5 },
    { attackerTypeId: getId('dragon'), defenderTypeId: getId('fairy'), effectivness: 0 },
    { attackerTypeId: getId('dark'), defenderTypeId: getId('posion'), effectivness: 0.5 },
    { attackerTypeId: getId('dark'), defenderTypeId: getId('psychic'), effectivness: 2 },
    { attackerTypeId: getId('dark'), defenderTypeId: getId('ghost'), effectivness: 2 },
    { attackerTypeId: getId('dark'), defenderTypeId: getId('dark'), effectivness: 0.5 },
    { attackerTypeId: getId('dark'), defenderTypeId: getId('fairy'), effectivness: 0.5 },
    { attackerTypeId: getId('steel'), defenderTypeId: getId('fire'), effectivness: 0.5 },
    { attackerTypeId: getId('steel'), defenderTypeId: getId('water'), effectivness: 0.5 },
    { attackerTypeId: getId('steel'), defenderTypeId: getId('electric'), effectivness: 0.5 },
    { attackerTypeId: getId('steel'), defenderTypeId: getId('ice'), effectivness: 2 },
    { attackerTypeId: getId('steel'), defenderTypeId: getId('rock'), effectivness: 2 },
    { attackerTypeId: getId('steel'), defenderTypeId: getId('steel'), effectivness: 0.5 },
    { attackerTypeId: getId('steel'), defenderTypeId: getId('fairy'), effectivness: 2 },
    { attackerTypeId: getId('fairy'), defenderTypeId: getId('fire'), effectivness: 0.5 },
    { attackerTypeId: getId('fairy'), defenderTypeId: getId('fighting'), effectivness: 2 },
    { attackerTypeId: getId('fairy'), defenderTypeId: getId('posion'), effectivness: 0.5 },
    { attackerTypeId: getId('fairy'), defenderTypeId: getId('dragon'), effectivness: 2 },
    { attackerTypeId: getId('fairy'), defenderTypeId: getId('dark'), effectivness: 2 },
    { attackerTypeId: getId('fairy'), defenderTypeId: getId('steel'), effectivness: 0.5 },
]);

await db.insert(moves).values([
    { id: 10, name: 'scratch', typeId: getId('normal'), manaCost: 2, attackBase: 20 },
    { id: 424, name: 'fire fang', typeId: getId('fire'), manaCost: 5, attackBase: 40 },
    { id: 163, name: 'slash', typeId: getId('normal'), manaCost: 4, attackBase: 35 },
    { id: 394, name: 'flare blitz', typeId: getId('fire'), manaCost: 10, attackBase: 80 },
    { id: 337, name: 'dragon claw', typeId: getId('dragon'), manaCost: 7, attackBase: 60 },
    { id: 9, name: 'thunder punch', typeId: getId('electric'), manaCost: 6, attackBase: 50 },
    { id: 344, name: 'volt tackle', typeId: getId('electric'), manaCost: 9, attackBase: 75 },
    { id: 231, name: 'iron tail', typeId: getId('steel'), manaCost: 6, attackBase: 55 },
    { id: 98, name: 'quick attack', typeId: getId('noral'), manaCost: 3, attackBase: 25 },
    { id: 528, name: 'wild charge', typeId: getId('electric'), manaCost: 8, attackBase: 70 },
    { id: 280, name: 'brick break', typeId: getId('fighting'), manaCost: 5, attackBase: 45 },
    { id: 34, name: 'body slam', typeId: getId('normal'), manaCost: 6, attackBase: 50 },
    { id: 2, name: 'karate chop', typeId: getId('fighting'), manaCost: 3, attackBase: 30 },
    { id: 67, name: 'low kick', typeId: getId('fighting'), manaCost: 4, attackBase: 35 },
    { id: 157, name: 'rock slide', typeId: getId('rock'), manaCost: 7, attackBase: 60 },
    { id: 66, name: 'submission', typeId: getId('fighting'), manaCost: 8, attackBase: 65 },
    { id: 530, name: 'dual chop', typeId: getId('dragon'), manaCost: 6, attackBase: 50 },
    { id: 223, name: 'dynamic punch', typeId: getId('fighting'), manaCost: 10, attackBase: 85 },
    { id: 33, name: 'tackle', typeId: getId('normal'), manaCost: 2, attackBase: 15 },
    { id: 401, name: 'aqua tail', typeId: getId('water'), manaCost: 6, attackBase: 50 },
    { id: 44, name: 'bite', typeId: getId('dark'), manaCost: 5, attackBase: 40 },
    { id: 127, name: 'waterfall', typeId: getId('water'), manaCost: 7, attackBase: 55 },
    { id: 8, name: 'ice punch', typeId: getId('ice'), manaCost: 6, attackBase: 50 },
    { id: 229, name: 'rapid spin', typeId: getId('normal'), manaCost: 3, attackBase: 20 },
    { id: 89, name: 'earthquake', typeId: getId('ground'), manaCost: 8, attackBase: 90 },
    { id: 242, name: 'crunch', typeId: getId('dark'), manaCost: 10, attackBase: 50 },
    { id: 163, name: 'slash', typeId: getId('normal'), manaCost: 6, attackBase: 35 },
    { id: 370, name: 'close combat', typeId: getId('fighting'), manaCost: 9, attackBase: 80 },
    { id: 404, name: 'x-scissor', typeId: getId('bug'), manaCost: 7, attackBase: 60 },
]);

await db.insert(pokemons).values([
    { id: 4, defenseBase: 30, healthPointsBase: 39 },
    { id: 5, defenseBase: 40, healthPointsBase: 55 },
    { id: 25, defenseBase: 35, healthPointsBase: 70 },
    { id: 26, defenseBase: 45, healthPointsBase: 45 },
    { id: 66, defenseBase: 50, healthPointsBase: 60 },
    { id: 67, defenseBase: 60, healthPointsBase: 70 },
    { id: 7, defenseBase: 45, healthPointsBase: 60 },
    { id: 8, defenseBase: 55, healthPointsBase: 80 },
    { id: 445, defenseBase: 75, healthPointsBase: 100 },
    { id: 335, defenseBase: 40, healthPointsBase: 60 },
]);

await db.insert(pokemonsTypes).values([
    { pokemonId: 4, typeId: getId('fire') },
    { pokemonId: 5, typeId: getId('fire') },
    { pokemonId: 25, typeId: getId('electric') },
    { pokemonId: 26, typeId: getId('electric') },
    { pokemonId: 66, typeId: getId('fighting') },
    { pokemonId: 67, typeId: getId('fighting') },
    { pokemonId: 7, typeId: getId('water') },
    { pokemonId: 8, typeId: getId('water') },
    { pokemonId: 445, typeId: getId('dragon') },
    { pokemonId: 445, typeId: getId('ground') },
    { pokemonId: 335, typeId: getId('fire') },
])